server:
  port: 9999

spring:
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/rinha2025
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG

payment-processors:
  default:
    host: ${PAYMENT_PROCESSOR_DEFAULT_HOST:http://payment-processor-default:8080}
  secondary:
    host: ${PAYMENT_PROCESSOR_SECONDARY_HOST:http://payment-processor-fallback:8080}
